export {default as Ciudad} from './ciudad'
export {default as Departamento} from './departamentos'
export {default as Pais}  from './paises'
export {default as TipoEmpleado}  from './tipoEmpleado'
export {default as TiposContratacion}  from './tipoContratacion'
export {default as Facultades}  from './facultades'
export {default as Areas}  from './areas'
export {default as Programas}  from './programas'